#!/bin/sh
export PATH=/opt/bin:/opt/sbin:$PATH

SCRIPT=/opt/local//opt/local/synology-xmpp/server.py
PIDFILE=/var/run/synology-xmpp.pid

case "$1" in
    start)
        echo "Starting synology-xmpp daemon"
	     [ -x $SCRIPT ] && $SCRIPT -d && echo $! > $PIDFILE
    ;;
    stop)
		echo "Stopping synology-xmpp daemon"
		kill `cat $PIDFILE` && rm $PIDFILE
	;;
    *)
        echo "Usage: $0 {start/stop}"
        exit 1
esac

exit 0